import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from 'docx'

function sectionParagraphs(section) {
  const items = [
    new Paragraph({
      text: section.heading,
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
    }),
    new Paragraph({
      children: [new TextRun(section.body || '')],
      spacing: { after: 120 },
    }),
  ]
  if (section.bullets?.length) {
    for (const b of section.bullets) {
      items.push(new Paragraph({ text: b, bullet: { level: 0 } }))
    }
  }
  if (section.table?.rows?.length) {
    items.push(new Paragraph({
      children: [new TextRun({ text: section.table.headers.join(' | '), bold: true })],
    }))
    for (const row of section.table.rows) {
      items.push(new Paragraph({ children: [new TextRun(row.join(' | '))] }))
    }
  }
  return items
}

export async function exportDocx(document) {
  const children = [
    new Paragraph({
      children: [new TextRun({ text: document.title, bold: true, size: 32 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun(document.tenantName)],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun(`Period: ${document.periodStart} to ${document.periodEnd}`)],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  ]

  if (document.offline) {
    children.push(new Paragraph({
      children: [new TextRun({ text: 'AI offline — deterministic content', italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }))
  }

  for (const section of document.sections) {
    children.push(...sectionParagraphs(section))
  }

  children.push(new Paragraph({
    children: [new TextRun({ text: 'Generated by SustainAlign', size: 18 })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
  }))

  const doc = new Document({ sections: [{ children }] })
  return Packer.toBuffer(doc)
}
