import PDFDocument from 'pdfkit'

export function exportPdf(document) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 })
    const chunks = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    doc.fontSize(20).text(document.title, { align: 'center' })
    doc.moveDown()
    doc.fontSize(12).text(document.tenantName, { align: 'center' })
    doc.text(`Period: ${document.periodStart} to ${document.periodEnd}`, { align: 'center' })
    if (document.offline) {
      doc.fontSize(9).fillColor('#666').text('(AI offline — deterministic content)', { align: 'center' })
      doc.fillColor('#000')
    }
    doc.moveDown(2)

    for (const section of document.sections) {
      doc.fontSize(14).text(section.heading, { underline: true })
      doc.moveDown(0.5)
      doc.fontSize(10)
      if (section.body) doc.text(section.body)
      if (section.bullets?.length) {
        doc.moveDown(0.3)
        for (const b of section.bullets) {
          doc.text(`• ${b}`, { indent: 10 })
        }
      }
      if (section.table?.rows?.length) {
        doc.moveDown(0.5)
        doc.fontSize(9).text(section.table.headers.join(' | '))
        for (const row of section.table.rows) {
          doc.text(row.join(' | '))
        }
      }
      doc.moveDown(1.5)
    }

    doc.fontSize(8).text('Generated by SustainAlign', { align: 'center' })
    doc.end()
  })
}
