import PptxGenJS from 'pptxgenjs'

export async function exportPptx(document) {
  const pptx = new PptxGenJS()
  pptx.author = 'SustainAlign'
  pptx.title = document.title

  const titleSlide = pptx.addSlide()
  titleSlide.addText(document.title, { x: 0.5, y: 1.5, w: 9, h: 1.5, fontSize: 28, bold: true, align: 'center' })
  titleSlide.addText(document.tenantName, { x: 0.5, y: 3, w: 9, h: 0.6, fontSize: 16, align: 'center' })
  titleSlide.addText(`${document.periodStart} — ${document.periodEnd}`, { x: 0.5, y: 3.6, w: 9, h: 0.5, fontSize: 12, align: 'center', color: '666666' })
  if (document.offline) {
    titleSlide.addText('AI offline — deterministic content', { x: 0.5, y: 4.3, w: 9, h: 0.4, fontSize: 10, align: 'center', color: '999999' })
  }

  for (const section of document.sections) {
    const slide = pptx.addSlide()
    slide.addText(section.heading, { x: 0.5, y: 0.4, w: 9, h: 0.8, fontSize: 22, bold: true, color: '059669' })

    const bodyText = section.body || ''
    const maxLen = 800
    slide.addText(bodyText.slice(0, maxLen), {
      x: 0.5,
      y: 1.3,
      w: 9,
      h: 3.5,
      fontSize: 12,
      valign: 'top',
      wrap: true,
    })

    if (section.bullets?.length) {
      const bulletText = section.bullets.slice(0, 6).map((b) => ({ text: b, options: { fontSize: 11, breakLine: true } }))
      slide.addText(bulletText, { x: 0.5, y: 4.2, w: 9, h: 1.2, fontSize: 11 })
    }
  }

  const footerSlide = pptx.addSlide()
  footerSlide.addText('Generated by SustainAlign', { x: 0.5, y: 2.5, w: 9, h: 0.5, fontSize: 14, align: 'center', color: '666666' })

  return pptx.write({ outputType: 'nodebuffer' })
}
