export const ROUTES = {
  home: '/',
  about: '/about',
  features: '/features',
  pricing: '/pricing',
  contact: '/contact',
  demo: '/demo',
  careers: '/careers',
  privacy: '/privacy',
  terms: '/terms',
  blog: '/blog',
  blogPost: (slug) => `/blog/${slug}`,
  ngos: '/ngos',
  ngoProfile: (slug) => `/ngos/${slug}`,
  caseStudies: '/case-studies',
  caseStudy: (slug) => `/case-studies/${slug}`,
  corporateSignup: '/signup/corporate',
  corporateLogin: '/login/corporate',
  ngoSignup: '/signup/ngo',
  ngoVerification: '/signup/ngo/verification',
  ngoLogin: '/login/ngo',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  mfa: '/auth/mfa',
  inviteTeam: '/onboarding/invite-team',
  dashboard: '/dashboard',
}

export const CORPORATE_ROUTES = {
  home: '/dashboard',
  discovery: '/dashboard/discovery',
  ngoProfile: (slug) => `/dashboard/ngos/${slug}`,
  projects: '/dashboard/projects',
  projectDetail: (id) => `/dashboard/projects/${id}`,
  compliance: '/dashboard/compliance',
  reporting: '/dashboard/reporting',
  copilot: '/dashboard/copilot',
  funds: '/dashboard/funds',
  volunteers: '/dashboard/volunteers',
  documents: '/dashboard/documents',
  communications: '/dashboard/communications',
  settings: '/dashboard/settings',
}
