import PDFDocument from 'pdfkit'
import { eq, desc } from 'drizzle-orm'
import { db } from '../../db/index.js'
import { reports, tenants, files as filesTable } from '../../db/schema.js'
import { newId } from '../../lib/ids.js'
import { storeFile } from '../files/index.js'
import { aggregateForTenant } from '../impact/index.js'
import { getComplianceSummary } from '../compliance/index.js'
import { listProjects } from '../projects/index.js'

function httpError(message, status) {
  const err = new Error(message)
  err.status = status
  return err
}

const TYPE_TITLES = {
  quarterly: 'Quarterly CSR Report',
  board: 'Board CSR Summary',
  sdg: 'SDG Impact Summary',
  impact: 'Impact Report',
  mca_csr2: 'MCA CSR-2 Preview',
}

function buildPdfBuffer({ title, tenantName, periodStart, periodEnd, sections }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 })
    const chunks = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    doc.fontSize(20).text(title, { align: 'center' })
    doc.moveDown()
    doc.fontSize(12).text(`${tenantName}`, { align: 'center' })
    doc.text(`Period: ${periodStart} to ${periodEnd}`, { align: 'center' })
    doc.moveDown(2)

    for (const section of sections) {
      doc.fontSize(14).text(section.heading, { underline: true })
      doc.moveDown(0.5)
      doc.fontSize(10).text(section.body)
      doc.moveDown(1.5)
    }

    doc.fontSize(8).text('Generated by SustainAlign', { align: 'center' })
    doc.end()
  })
}

function buildReportSections(type, aggregate, compliance, projectList) {
  const sections = []

  sections.push({
    heading: 'Impact Summary',
    body: [
      `Total Beneficiaries: ${aggregate.impactSummary.totalBeneficiaries.toLocaleString('en-IN')}`,
      `Active Projects: ${aggregate.impactSummary.projectsActive}`,
      `SDGs Covered: ${aggregate.impactSummary.sdgsCovered}`,
      `CO₂ Offset (tons): ${aggregate.impactSummary.co2Offset}`,
    ].join('\n'),
  })

  if (type === 'sdg' || type === 'quarterly' || type === 'board') {
    const sdgLines = aggregate.sdgMapping.map((s) =>
      `SDG ${s.sdg} ${s.label}: ${s.projects} project(s), spend ₹${s.spend.toLocaleString('en-IN')}`)
    sections.push({ heading: 'SDG Mapping', body: sdgLines.join('\n') || 'No SDG data yet.' })
  }

  if (type === 'quarterly' || type === 'board' || type === 'mca_csr2') {
    sections.push({
      heading: 'Compliance (Section 135)',
      body: [
        `FY: ${compliance.section135.fy}`,
        `Eligible: ${compliance.section135.eligible ? 'Yes' : 'No'}`,
        `Formula: ${compliance.section135.obligationBreakdown?.formula || 'N/A'}`,
        `CSR Obligation (2%): ₹${compliance.section135.csrObligation.toLocaleString('en-IN')}`,
        `Total Spent: ₹${compliance.spend.spent.toLocaleString('en-IN')}`,
        `Unspent: ₹${compliance.spend.unspent.toLocaleString('en-IN')}`,
      ].join('\n'),
    })
  }

  if (type === 'mca_csr2' || type === 'board') {
    const validationLines = compliance.scheduleVIIValidation
      .map((v) => `${v.item}: ${v.status}${v.note ? ` (${v.note})` : ''}`)
    sections.push({
      heading: 'Schedule VII Validation',
      body: validationLines.join('\n') || 'No validation data.',
    })
    const schedLines = compliance.spend.breakdown
      .map((b) => `${b.category} | ${b.scheduleVII} | ₹${b.amount.toLocaleString('en-IN')}`)
    sections.push({
      heading: 'Schedule VII Spend Breakdown',
      body: schedLines.join('\n') || 'No spend data.',
    })
  }

  if (type === 'board' || type === 'quarterly') {
    const perf = aggregate.ngoPerformance.slice(0, 5)
      .map((n) => `${n.ngo}: score ${n.score}, on-time ${n.onTime}%`)
    sections.push({ heading: 'NGO Performance', body: perf.join('\n') || 'No performance data.' })
  }

  const projLines = projectList.projects.slice(0, 10)
    .map((p) => `${p.name} — ${p.ngoName || 'NGO'} — ${p.progress}% — ₹${(p.spentInr || 0).toLocaleString('en-IN')} spent`)
  sections.push({ heading: 'Projects', body: projLines.join('\n') || 'No projects.' })

  return sections
}

export function listReports(corporateTenantId) {
  return db.select().from(reports)
    .where(eq(reports.corporateTenantId, corporateTenantId))
    .orderBy(desc(reports.createdAt))
    .all()
    .map((r) => ({
      id: r.id,
      type: r.type,
      title: r.title,
      periodStart: r.periodStart,
      periodEnd: r.periodEnd,
      status: r.status,
      fileId: r.fileId,
      downloadUrl: r.fileId ? `/api/files/${r.fileId}/download` : null,
      createdAt: r.createdAt,
    }))
}

export async function generateReport({
  corporateTenantId,
  userId,
  type,
  periodStart,
  periodEnd,
  req,
}) {
  if (!TYPE_TITLES[type]) throw httpError('Invalid report type', 400)

  const tenant = db.select().from(tenants).where(eq(tenants.id, corporateTenantId)).get()
  const aggregate = aggregateForTenant(corporateTenantId)
  const compliance = getComplianceSummary(corporateTenantId)
  const projectList = listProjects({ corporateTenantId, audience: 'corporate' })

  const title = TYPE_TITLES[type]
  const sections = buildReportSections(type, aggregate, compliance, projectList)
  const buffer = await buildPdfBuffer({
    title,
    tenantName: tenant?.name || 'Corporate',
    periodStart,
    periodEnd,
    sections,
  })

  const now = new Date()
  const reportId = newId()

  const stored = await storeFile({
    req,
    buffer,
    tenantId: corporateTenantId,
    tenantType: 'corporate',
    uploadedBy: userId,
    category: 'report',
    originalName: `${type}-${periodStart}-${periodEnd}.pdf`,
    mime: 'application/pdf',
    entityType: 'report',
    entityId: reportId,
  })

  db.insert(reports).values({
    id: reportId,
    corporateTenantId,
    type,
    title,
    periodStart,
    periodEnd,
    status: 'generated',
    fileId: stored.id,
    metadataJson: JSON.stringify({ sectionCount: sections.length }),
    createdBy: userId,
    createdAt: now,
    updatedAt: now,
  }).run()

  return {
    id: reportId,
    type,
    title,
    periodStart,
    periodEnd,
    status: 'generated',
    fileId: stored.id,
    downloadUrl: `/api/files/${stored.id}/download`,
  }
}

export function getReport(id, corporateTenantId) {
  const row = db.select().from(reports).where(eq(reports.id, id)).get()
  if (!row || row.corporateTenantId !== corporateTenantId) return null
  return {
    ...row,
    downloadUrl: row.fileId ? `/api/files/${row.fileId}/download` : null,
  }
}

export function submitReport(id, corporateTenantId) {
  const row = getReport(id, corporateTenantId)
  if (!row) throw httpError('Report not found', 404)
  db.update(reports)
    .set({ status: 'submitted', updatedAt: new Date() })
    .where(eq(reports.id, id))
    .run()
  return { id, status: 'submitted' }
}
